public class DAY18 {
    public static void main(String[] args) {
        System.out.println("membuat variabel dengan tipe data boolean");
        int w,n;
        w= 90;
        n= 50;
        
        boolean hasil= w > n;
        boolean hasil2= w < n;
        System.out.println("hasil nya adalah : "+hasil);  //true
        System.out.println("hasil nya adalah : "+hasil2); //false
        //boolean adalah tipe data yang hanya menyimpan value atau nilai yaitu true or false
    }
    
}
