public class Day16 {
    public static void main (String[] args){
        
        /*pada tipe data float terdapat huruf "f" sesudah
         * angka desimal,agar bisa membedakan antara tipe
         * data float dan double
         */
         
        float anggi,angga;
        anggi = 125.3f; 
        angga = 130.5f;
        System.out.println("tinggi badan anggi "+anggi+"cm");
        System.out.println("tinggi badan angga "+angga+"cm");
        
        /*dalam matematika bilangan pecahan atau desimal biasanya
         * menggunakan tanda koma tetapi dalam bahasa pemrograman
         * tanda koma di ganti dengan titik begitu pula sebaliknya
         */
        
    }
}
