public class DAY23 {
    public static void main(String[] args) {
        System.out.println("membuat variabel tipe data reference:Long");
      
        Long nmbr = 5000L; 
        Long nmbr1 = 300L;
        System.out.println(nmbr);
        System.out.println(nmbr1); 
        
        System.out.println("hasil penjumlahan di atas adalah");
        System.out.println(nmbr+nmbr1);        
    }
}
