public class DAY22 {
    public static void main(String[] args) {
        Integer money,money1;
        money = 30000;
        money1= 8000;
         
        System.out.println("total nilai awal");
        System.out.println(money);//uang saya
        System.out.println(money1);//uang "DIA"
        
        money =2000;
        money1=30000;
        System.out.println("nilai akhir");
        System.out.println(money);//na pinjam uangku 28.000 jadi sisa 2000 uangku
        System.out.println(money1);
        
    }
}
