public class DAY38 {
    public static void main(String[] args) {
        System.out.println("operator penugasan");
        //pengisian dengan perkalian dan pembagian
        
        int x = 15;
        //pengisian dan perkalian
        x *= 15;
        System.out.println("hasil perkalian: "+x);
        
        //pengisian dan perkalian
        x /= 5;
        System.out.println("hasil pembagian: "+x);
        
    }
}
