public class DAY37 {
    public static void main(String[] args) {
        System.out.println("operator penugasan");
        //pengisian nilai,penambahan dan pengurangan
        
        int x = 20;
        //pengisisan nilai
        x = 20;
        System.out.println("hasil pengisian: "+x);
        
        //pengisian dan penambahan
        x += 15;
        System.out.println("hasil tambah: "+x);
        
        //pengisian dan pengurangan
        x -= 5;
        System.out.println("hasil kurang: "+x);
        
        
    }
 
}
