public class Day3 {
    
    public static void main(String[] args) {
        System.out.println("Pemrograman hari 3");
        System.out.println("+-------------+----------+");
        System.out.println("| Mata Kuliah |   SKS    |");
        System.out.println("+-------------+----------+");
        System.out.println("|     DDP     |    3     |");
        System.out.println("+ ___________ + ________ +");
        System.out.println("|     AOK     |    3     |");
        System.out.println("+ ___________ + ________ +");
        System.out.println("|    Agama    |    2     |");
        System.out.println("+_____________+__________+");
        
        
        
    }
    
}
