public class DAY43 {
    public static void main(String[] args) {
        
    System.out.println("operator perbandingan");
        
        int x,y;
        x = 20;
        y = 35;
        
        //lebih besar sama dengan
        System.out.println("apakah x >= Y: "+(x >= y));//false
        
         //lebih kecil sama dengan
        System.out.println("apakah x <= y: "+(x <= y));//true
        
  }
}
