public class DAY46 {
    public static void main(String[] args) {
         System.out.println("operator: NOT");
        
        boolean x,y;
        x = 40 > 20;
        y = 55 < 44;
        
        System.out.println(!x);//false
        System.out.println(!y);//true
        
        /*Operator logika/kebalikan negasi digunakan untuk membalik nilai boolean
        jika kita menghasilkan nilai true maka nilainya akan diubah menjadi false
        begitu pula sebaliknya
        */
    }
}
