public class Day5 {
    public static void main(String[] args){
        
        System.out.println("Pemrogrman hari ke 5");
        
        //hasil penjumlahan antara kucing dan anjing
        
        int anjing,kucing;
        anjing = 5;
        kucing = 8;
        System.out.println(anjing + kucing);
        
        /* menjumlahkan semua hewan yang ada di kebun binatang
         * yaitu jerapah,beruang dan gajah
         */
        
        int jerapah,beruang,gajah;
        jerapah = 6;
        beruang = 2;
        gajah   = 4;
        System.out.println(jerapah+beruang+gajah);
        
        
        
        
    }
    
}
