public class Day6 {
    public static void main(String[] args){
        System.out.println("Pemrograman hari ke 6");
        System.out.println("_____________________");
        
        //membuat deklarasi
        int melati,anggrek;
        
        melati  = 50;
        anggrek = 50;
        
        System.out.printf("banyak melati  = %d \n",melati);
        System.out.printf("banyak anggrek = %d \n",anggrek);
        
    }
    
    
}
