public class Day7{
    public static void main(String[] args){
        System.out.println("Pemrograman hari ke 7 membuat inisialisasi");
        
        int angka = 50; //variabel angka di inisialisasi kan dengan angka 50
        int buku  = 10; //variabel buku di inisialisasi kan dengan angka 10
        
        System.out.println("angka: "+ angka);
        System.out.println("buku: "+ buku);
        
        
    }
}
